// Code generated by goyacc -o lyx/gram.go -p yy lyx/gram.y. DO NOT EDIT.

//line lyx/gram.y:3
package lyx

import __yyfmt__ "fmt"

//line lyx/gram.y:3

import (
	"crypto/rand"
	"encoding/hex"
)

func randomHex(n int) (string, error) {
	bytes := make([]byte, n)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

//line lyx/gram.y:21
type yySymType struct {
	yys     int
	str     string
	strlist []string
	byte    byte
	bytes   []byte
	int     int
	bool    bool
	empty   struct{}

	statement Statement
	from_list []FromClauseNode
	from      FromClauseNode
	tableelt  []TableElt
	tableref  FromClauseNode

	selectStmt *Select

	colref ColumnRef

	aexpr AExpr

	aexprList []AExpr
}

const SCONST = 57346
const IDENT = 57347
const CREATE = 57348
const ALTER = 57349
const ROLE = 57350
const DATABASE = 57351
const NATURAL = 57352
const TABLE = 57353
const INDEX = 57354
const SELECT = 57355
const UPDATE = 57356
const INSERT = 57357
const DELETE = 57358
const FROM = 57359
const WHERE = 57360
const AND = 57361
const VALUES = 57362
const OR = 57363
const EXPLAIN = 57364
const EXECUTE = 57365
const PREPARE = 57366
const BEGIN = 57367
const COMMIT = 57368
const ROLLBACK = 57369
const VACUUM = 57370
const CLUSTER = 57371
const ANALYZE = 57372
const INTO = 57373
const OUTER_P = 57374
const FULL = 57375
const RIGHT = 57376
const LEFT = 57377
const INNER_P = 57378
const DROP = 57379
const TRUNCATE = 57380
const FETCH = 57381
const FOR = 57382
const ORDER = 57383
const GROUP = 57384
const BY = 57385
const OFFSET = 57386
const LIMIT = 57387
const WINDOW = 57388
const CROSS = 57389
const SET = 57390
const RESET = 57391
const LOCAL = 57392
const ALL = 57393
const PRIMARY = 57394
const KEY = 57395
const FOREIGN = 57396
const REFERENCES = 57397
const USING = 57398
const TCOLON = 57399
const TCOMMA = 57400
const TOPENBR = 57401
const TCLOSEBR = 57402
const TSQOPENBR = 57403
const TSQCLOSEBR = 57404
const TSEMICOLON = 57405
const TNOT_EQUALS = 57406
const TDOT = 57407
const NULL_P = 57408
const ISNULL = 57409
const ON = 57410
const JOIN = 57411
const TPLUS = 57412
const TMINUS = 57413
const TMUL = 57414
const TDIV = 57415
const TGREATER = 57416
const TGREATER_EQUALS = 57417
const TLESS = 57418
const TLESS_EQUALS = 57419
const TMOD = 57420
const TPOW = 57421
const FALSE_P = 57422
const TRUE_P = 57423
const TEQ = 57424
const OP = 57425
const ONLY = 57426
const RETURNING = 57427
const COPY = 57428
const IS = 57429
const NOT = 57430
const NULL = 57431
const DISTINCT = 57432
const DEFAULT = 57433
const NORMALIZED = 57434
const NOTNULL = 57435
const DOCUMENT_P = 57436
const TO = 57437
const STDOUT = 57438
const AS = 57439

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"SCONST",
	"IDENT",
	"CREATE",
	"ALTER",
	"ROLE",
	"DATABASE",
	"NATURAL",
	"TABLE",
	"INDEX",
	"SELECT",
	"UPDATE",
	"INSERT",
	"DELETE",
	"FROM",
	"WHERE",
	"AND",
	"VALUES",
	"OR",
	"EXPLAIN",
	"EXECUTE",
	"PREPARE",
	"BEGIN",
	"COMMIT",
	"ROLLBACK",
	"VACUUM",
	"CLUSTER",
	"ANALYZE",
	"INTO",
	"OUTER_P",
	"FULL",
	"RIGHT",
	"LEFT",
	"INNER_P",
	"DROP",
	"TRUNCATE",
	"FETCH",
	"FOR",
	"ORDER",
	"GROUP",
	"BY",
	"OFFSET",
	"LIMIT",
	"WINDOW",
	"CROSS",
	"SET",
	"RESET",
	"LOCAL",
	"ALL",
	"PRIMARY",
	"KEY",
	"FOREIGN",
	"REFERENCES",
	"USING",
	"TCOLON",
	"TCOMMA",
	"TOPENBR",
	"TCLOSEBR",
	"TSQOPENBR",
	"TSQCLOSEBR",
	"TSEMICOLON",
	"TNOT_EQUALS",
	"TDOT",
	"NULL_P",
	"ISNULL",
	"ON",
	"JOIN",
	"TPLUS",
	"TMINUS",
	"TMUL",
	"TDIV",
	"TGREATER",
	"TGREATER_EQUALS",
	"TLESS",
	"TLESS_EQUALS",
	"TMOD",
	"TPOW",
	"FALSE_P",
	"TRUE_P",
	"TEQ",
	"OP",
	"ONLY",
	"RETURNING",
	"COPY",
	"IS",
	"NOT",
	"NULL",
	"DISTINCT",
	"DEFAULT",
	"NORMALIZED",
	"NOTNULL",
	"DOCUMENT_P",
	"TO",
	"STDOUT",
	"AS",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line lyx/gram.y:1469

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 150,
	59, 91,
	-2, 73,
	-1, 241,
	19, 43,
	21, 43,
	60, 43,
	64, 43,
	67, 43,
	70, 43,
	71, 43,
	72, 43,
	73, 43,
	74, 43,
	75, 43,
	76, 43,
	77, 43,
	78, 43,
	79, 43,
	82, 43,
	83, 43,
	87, 43,
	93, 43,
	-2, 105,
}

const yyPrivate = 57344

const yyLast = 1073

var yyAct = [...]int{

	152, 342, 321, 348, 335, 210, 164, 286, 269, 305,
	253, 204, 59, 261, 147, 17, 214, 201, 139, 154,
	290, 51, 249, 349, 215, 213, 155, 50, 52, 54,
	56, 37, 39, 38, 40, 319, 207, 160, 337, 301,
	22, 300, 158, 57, 203, 58, 58, 58, 58, 58,
	51, 58, 43, 140, 161, 292, 382, 293, 157, 364,
	264, 266, 265, 267, 185, 58, 186, 232, 359, 315,
	310, 58, 281, 58, 379, 129, 130, 131, 132, 328,
	137, 235, 234, 51, 314, 318, 289, 246, 208, 233,
	196, 236, 292, 238, 159, 237, 304, 350, 171, 259,
	162, 250, 163, 371, 41, 351, 295, 51, 327, 183,
	247, 297, 188, 270, 51, 172, 173, 174, 175, 179,
	182, 178, 181, 176, 177, 354, 316, 180, 184, 51,
	366, 355, 187, 274, 298, 257, 330, 216, 189, 169,
	377, 191, 190, 373, 306, 153, 42, 276, 275, 58,
	58, 58, 3, 282, 158, 158, 255, 277, 202, 279,
	55, 278, 211, 311, 44, 45, 46, 47, 48, 280,
	197, 198, 158, 205, 53, 49, 199, 156, 166, 167,
	168, 135, 136, 37, 133, 134, 51, 263, 209, 165,
	317, 239, 200, 370, 326, 149, 151, 192, 193, 194,
	158, 1, 195, 376, 251, 372, 365, 353, 329, 254,
	264, 266, 265, 267, 296, 271, 248, 158, 256, 252,
	205, 268, 285, 288, 260, 245, 217, 218, 219, 220,
	221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
	231, 272, 273, 313, 244, 336, 262, 202, 287, 21,
	243, 202, 14, 13, 12, 263, 11, 10, 16, 15,
	158, 283, 6, 158, 284, 258, 294, 205, 291, 5,
	4, 309, 9, 8, 20, 307, 308, 303, 264, 266,
	265, 267, 19, 18, 7, 299, 142, 242, 302, 138,
	322, 212, 260, 254, 320, 170, 323, 2, 0, 0,
	0, 158, 158, 324, 0, 158, 0, 0, 58, 0,
	0, 271, 58, 58, 262, 0, 0, 287, 0, 339,
	0, 0, 0, 345, 344, 346, 333, 334, 58, 352,
	338, 0, 0, 0, 312, 0, 0, 325, 158, 356,
	0, 331, 332, 0, 0, 0, 0, 0, 0, 361,
	0, 322, 0, 363, 0, 0, 0, 341, 0, 0,
	0, 0, 369, 358, 58, 340, 0, 0, 343, 58,
	58, 0, 375, 347, 0, 0, 0, 0, 0, 0,
	381, 58, 0, 0, 0, 0, 0, 0, 58, 0,
	357, 0, 58, 362, 0, 0, 0, 0, 367, 368,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	374, 0, 0, 0, 343, 0, 0, 378, 0, 0,
	0, 380, 60, 150, 82, 83, 90, 91, 0, 71,
	89, 62, 63, 64, 65, 66, 67, 68, 70, 69,
	72, 73, 74, 75, 76, 77, 84, 85, 86, 95,
	0, 0, 0, 0, 0, 87, 88, 99, 98, 92,
	93, 94, 97, 96, 0, 118, 78, 79, 80, 81,
	110, 108, 109, 111, 0, 103, 102, 148, 101, 0,
	0, 105, 127, 0, 0, 0, 122, 117, 143, 144,
	112, 116, 125, 126, 123, 124, 114, 115, 121, 120,
	0, 128, 104, 107, 0, 119, 145, 0, 0, 146,
	0, 0, 0, 0, 0, 106, 60, 150, 82, 83,
	90, 91, 0, 71, 89, 62, 63, 64, 65, 66,
	67, 68, 70, 69, 72, 73, 74, 75, 76, 77,
	84, 85, 86, 95, 0, 0, 0, 0, 0, 87,
	88, 99, 98, 92, 93, 94, 97, 96, 0, 118,
	78, 79, 80, 81, 110, 108, 109, 111, 0, 103,
	102, 148, 241, 0, 0, 105, 127, 0, 0, 0,
	122, 117, 143, 144, 112, 116, 125, 126, 123, 124,
	114, 115, 121, 120, 0, 128, 104, 107, 0, 119,
	145, 0, 0, 146, 0, 0, 0, 0, 0, 106,
	60, 150, 82, 83, 90, 91, 0, 71, 89, 62,
	63, 64, 65, 66, 67, 68, 70, 69, 72, 73,
	74, 75, 76, 77, 84, 85, 86, 95, 0, 0,
	0, 0, 0, 87, 88, 99, 98, 92, 93, 94,
	97, 96, 0, 118, 78, 79, 80, 81, 110, 108,
	109, 111, 0, 103, 102, 148, 101, 0, 0, 105,
	127, 0, 0, 0, 122, 117, 143, 144, 141, 116,
	125, 126, 123, 124, 114, 115, 121, 120, 0, 128,
	104, 107, 0, 119, 145, 0, 0, 146, 0, 0,
	0, 0, 0, 106, 60, 61, 82, 83, 90, 91,
	0, 71, 89, 62, 63, 64, 65, 66, 67, 68,
	70, 69, 72, 73, 74, 75, 76, 77, 84, 85,
	86, 95, 0, 0, 0, 0, 0, 87, 88, 99,
	98, 92, 93, 94, 97, 96, 0, 118, 78, 79,
	80, 81, 110, 108, 109, 111, 0, 103, 102, 100,
	101, 0, 0, 105, 127, 0, 0, 0, 122, 117,
	113, 0, 112, 116, 125, 126, 123, 124, 114, 115,
	121, 120, 0, 128, 104, 107, 0, 119, 0, 0,
	0, 206, 0, 82, 83, 90, 91, 106, 71, 89,
	62, 63, 64, 65, 66, 67, 68, 70, 69, 72,
	73, 74, 75, 76, 77, 84, 85, 86, 95, 0,
	0, 0, 0, 0, 87, 88, 99, 98, 92, 93,
	94, 97, 96, 0, 118, 78, 79, 80, 81, 110,
	108, 109, 111, 0, 103, 102, 100, 101, 0, 0,
	105, 127, 185, 0, 186, 122, 117, 113, 0, 112,
	116, 125, 126, 123, 124, 114, 115, 121, 120, 0,
	128, 104, 107, 0, 119, 0, 185, 0, 186, 0,
	0, 0, 0, 0, 106, 0, 0, 0, 0, 0,
	0, 360, 0, 0, 0, 0, 0, 183, 0, 0,
	188, 0, 0, 172, 173, 174, 175, 179, 182, 178,
	181, 176, 177, 0, 0, 180, 184, 240, 0, 0,
	187, 183, 0, 185, 188, 186, 189, 172, 173, 174,
	175, 179, 182, 178, 181, 176, 177, 0, 0, 180,
	184, 0, 0, 0, 187, 0, 0, 0, 0, 0,
	189, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 183, 0,
	0, 188, 0, 0, 172, 173, 174, 175, 179, 182,
	178, 181, 176, 177, 0, 0, 180, 184, 0, 0,
	0, 187, 35, 36, 0, 0, 0, 189, 0, 37,
	39, 38, 40, 0, 0, 0, 0, 0, 22, 26,
	29, 23, 24, 25, 30, 31, 32, 0, 0, 0,
	0, 0, 0, 34, 33, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 27, 28, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 41,
}
var yyPact = [...]int{

	986, -1000, -11, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -11, -11, -11,
	-11, -11, 18, -1000, -1000, -1000, 181, 124, 109, 181,
	700, 700, 700, 700, 700, 173, 700, 606, 114, -58,
	160, 181, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	700, -1000, -45, 181, -1000, -1000, 700, -1000, 700, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 184, 700, 700, 700, -1000, 81, -1000,
	45, -1000, -1000, 418, 418, 418, -1000, -1000, 418, -1000,
	-1000, -1000, 31, 181, 181, -1000, -58, 181, -21, -1000,
	787, -46, -1000, -1000, 29, -1000, -1000, -1000, -1000, 606,
	144, 78, 418, 418, 418, 418, 418, 418, 418, 418,
	418, 418, 418, 418, 418, 418, 418, 1, -1000, -1000,
	181, -1000, 904, 904, 904, 857, 512, 28, 62, 181,
	-73, -1000, 43, 181, -1000, -1000, -1000, 787, 102, -1000,
	93, 418, 41, 245, 16, -1000, 78, 904, 904, 904,
	904, 904, 904, 904, 904, 904, 904, 904, 904, 904,
	904, 904, -1000, 67, -1000, -1000, 152, -1000, -1000, -1000,
	-1000, -1000, 12, 904, 133, 170, 181, 181, 30, -76,
	181, -1000, -1000, -3, 787, 53, 65, 91, 904, 78,
	-28, -30, 78, 27, 112, 112, 112, -1000, -1000, -1000,
	181, -1000, 10, 245, -1000, -1000, -1000, 146, -1000, -1000,
	418, -1000, 25, -1000, 9, 68, -1000, -47, 144, 181,
	144, -1000, 102, 700, 56, 20, 95, 700, 700, 245,
	78, 78, 177, -31, 78, -1000, -1000, -1000, -1000, -1000,
	16, 418, 904, 700, 418, -1000, 181, 144, 184, 418,
	-62, -1000, 39, -1000, 34, -1000, -1000, 52, 181, 80,
	88, -1000, -1000, 245, 177, -1000, 418, 78, 245, -1000,
	904, -1000, 8, 833, -1000, -62, -1000, 904, -1000, 700,
	181, -1000, -1, 86, 700, 700, -1000, 904, 245, -1000,
	418, -1000, -1000, -1000, 48, 104, 700, -1000, -1000, -1000,
	-1000, 181, 100, 700, -1000, 15, -1000, 700, -1000, 181,
	-1000, -4, -1000,
}
var yyPgo = [...]int{

	0, 297, 152, 0, 11, 6, 5, 295, 291, 25,
	16, 24, 289, 289, 287, 53, 286, 286, 12, 284,
	15, 283, 282, 274, 273, 272, 270, 269, 262, 259,
	258, 257, 256, 254, 253, 252, 146, 249, 249, 249,
	17, 244, 1, 243, 225, 14, 223, 2, 222, 10,
	19, 221, 8, 43, 7, 221, 218, 214, 208, 207,
	206, 205, 203, 201, 196, 195, 195, 18, 194, 193,
	9, 13, 4, 192, 3, 190,
}
var yyR1 = [...]int{

	0, 63, 36, 36, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 45, 45, 45, 53, 53, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 4, 4, 5, 55, 55, 55, 55, 55,
	55, 55, 55, 55, 55, 64, 64, 14, 13, 13,
	65, 16, 16, 16, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 15, 39, 38,
	38, 17, 17, 17, 17, 17, 17, 17, 17, 17,
	17, 17, 17, 17, 17, 17, 6, 6, 66, 66,
	12, 12, 67, 67, 67, 67, 24, 24, 24, 24,
	26, 27, 28, 19, 25, 2, 2, 2, 2, 2,
	2, 68, 68, 69, 69, 49, 49, 49, 29, 29,
	29, 29, 30, 31, 32, 33, 35, 34, 56, 56,
	57, 57, 58, 58, 59, 59, 60, 60, 61, 61,
	62, 62, 7, 7, 8, 8, 10, 10, 52, 52,
	51, 51, 9, 9, 9, 70, 70, 71, 71, 71,
	71, 72, 11, 11, 11, 11, 11, 11, 20, 20,
	40, 40, 73, 73, 41, 44, 44, 42, 42, 43,
	74, 74, 21, 21, 50, 50, 75, 75, 48, 48,
	54, 22, 47, 47, 46, 46, 23, 37,
}
var yyR2 = [...]int{

	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 0, 2, 0, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 3, 4, 1, 1, 3,
	1, 1, 3, 1, 1, 2, 2, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 2, 3, 2, 4, 2, 3, 4, 3,
	4, 5, 6, 3, 4, 3, 4, 1, 3, 1,
	1, 2, 2, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 1, 0, 2, 1, 0,
	1, 3, 3, 2, 1, 1, 4, 5, 2, 2,
	1, 1, 1, 3, 3, 2, 2, 2, 2, 2,
	2, 0, 2, 0, 5, 3, 6, 3, 7, 3,
	3, 3, 2, 2, 2, 2, 2, 2, 0, 3,
	0, 2, 0, 3, 0, 2, 0, 2, 0, 2,
	0, 2, 2, 0, 1, 3, 1, 3, 2, 1,
	0, 1, 2, 1, 4, 1, 0, 2, 2, 2,
	1, 2, 3, 4, 5, 4, 5, 4, 11, 2,
	1, 3, 0, 1, 3, 0, 1, 1, 3, 3,
	0, 2, 7, 5, 0, 1, 0, 2, 1, 3,
	3, 8, 1, 3, 0, 2, 7, 6,
}
var yyChk = [...]int{

	-1000, -63, -1, -2, -26, -27, -28, -19, -24, -25,
	-31, -32, -33, -34, -35, -29, -30, -20, -21, -22,
	-23, -37, 22, 25, 26, 27, 23, 48, 49, 24,
	28, 29, 30, 38, 37, 6, 7, 13, 15, 14,
	16, 86, -36, 63, -36, -36, -36, -36, -36, -2,
	-3, 5, -3, 50, -3, 51, -3, -53, -45, -18,
	4, 5, 13, 14, 15, 16, 17, 18, 19, 21,
	20, 11, 22, 23, 24, 25, 26, 27, 48, 49,
	50, 51, 6, 7, 28, 29, 30, 37, 38, 12,
	8, 9, 41, 42, 43, 31, 45, 44, 40, 39,
	59, 60, 58, 57, 84, 63, 97, 85, 53, 54,
	52, 55, 72, 70, 78, 79, 73, 69, 47, 87,
	81, 80, 68, 76, 77, 74, 75, 64, 83, -53,
	-53, -53, -53, 11, 12, 8, 9, -53, -12, -67,
	-15, 72, -16, 70, 71, 88, 91, -45, 59, -65,
	5, -64, -3, 31, -50, 84, 17, -10, -3, -53,
	82, -3, -53, -53, -5, 5, -53, -53, -53, 58,
	-7, 17, 70, 71, 72, 73, 78, 79, 76, 74,
	82, 77, 75, 64, 83, 19, 21, 87, 67, 93,
	97, -3, -15, -15, -15, -15, 59, -10, -10, -50,
	-73, -40, -3, 65, -4, -18, 4, 82, 59, -67,
	-6, 18, -8, -9, -10, -11, 59, -15, -15, -15,
	-15, -15, -15, -15, -15, -15, -15, -15, -15, -15,
	-15, -15, 66, 88, 81, 80, 90, 94, 92, -3,
	60, 60, -14, -15, -41, -44, 59, 48, -10, 95,
	58, -3, -4, -49, -3, 54, -56, 42, -15, 58,
	47, -71, 69, 10, 33, 35, 34, 36, -51, -52,
	97, -3, -11, -9, 66, 81, 80, 90, 94, 92,
	17, 60, 20, -20, -40, -48, -54, -3, -46, 56,
	96, -40, 58, 60, -4, 53, -57, 46, 43, -9,
	69, 69, -9, -71, 69, -70, 32, -70, -70, -3,
	60, 17, -15, -43, 59, 60, 58, -75, 17, 82,
	-6, -47, -3, -6, -49, -53, -68, 52, 59, -58,
	41, -53, -53, -9, -9, -72, 68, 69, -9, -52,
	-15, -53, -42, -15, -54, -6, -5, -15, -74, 85,
	58, 53, -3, -59, 45, 43, -72, -15, -9, 60,
	58, -74, -53, -47, 60, -60, 44, -53, -53, -42,
	-69, 55, -61, 39, -53, -3, -62, 40, -53, 59,
	-53, -3, 60,
}
var yyDef = [...]int{

	76, -2, 2, 77, 78, 79, 80, 81, 82, 83,
	84, 85, 86, 87, 88, 89, 90, 2, 2, 2,
	2, 2, 0, 180, 181, 182, 0, 0, 0, 0,
	74, 74, 74, 74, 74, 0, 74, 0, 0, 264,
	0, 0, 1, 3, 185, 186, 187, 188, 189, 190,
	74, 91, 0, 0, 178, 179, 74, 203, 74, 71,
	72, 73, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 204,
	205, 207, 206, 0, 74, 74, 74, 202, 223, 170,
	174, 54, 114, 55, 0, 0, 147, 111, 42, 113,
	-2, 110, 0, 0, 0, 265, 264, 252, 226, 183,
	0, 0, 184, 75, 0, 94, 199, 200, 201, 0,
	166, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 134, 136,
	0, 173, 115, 116, 132, 0, 0, 255, 0, 0,
	0, 253, 250, 0, 176, 92, 93, 0, 0, 171,
	208, 0, 222, 224, 230, 233, 0, 117, 118, 119,
	120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
	130, 131, 133, 0, 137, 139, 0, 143, 145, 172,
	112, -2, 0, 107, 256, 0, 0, 0, 274, 0,
	0, 227, 177, 0, 0, 0, 210, 0, 167, 0,
	0, 0, 0, 0, 236, 236, 236, 240, 232, 231,
	0, 229, 233, 0, 135, 138, 140, 0, 144, 146,
	0, 106, 0, 263, 0, 266, 268, 0, 166, 0,
	166, 251, 0, 74, 191, 0, 212, 74, 74, 225,
	0, 0, 0, 0, 0, 237, 235, 238, 239, 228,
	242, 0, 141, 74, 0, 254, 0, 166, 0, 0,
	260, 275, 272, 277, 197, 198, 195, 0, 0, 214,
	0, 211, 209, 243, 0, 245, 0, 0, 247, 234,
	142, 262, 0, 257, 269, 260, 267, 270, 276, 74,
	0, 192, 0, 216, 74, 74, 244, 241, 246, 259,
	0, 271, 261, 273, 193, 218, 74, 215, 213, 258,
	196, 0, 220, 74, 217, 0, 248, 74, 219, 0,
	221, 0, 194,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:238
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:239
		{

		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:245
		{
			yyVAL.str = yyDollar[1].str
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:246
		{
			yyVAL.str = yyDollar[1].str
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:247
		{
			yyVAL.str = yyDollar[1].str
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:248
		{
			yyVAL.str = yyDollar[1].str
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:249
		{
			yyVAL.str = yyDollar[1].str
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:250
		{
			yyVAL.str = yyDollar[1].str
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:251
		{
			yyVAL.str = yyDollar[1].str
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:252
		{
			yyVAL.str = yyDollar[1].str
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:253
		{
			yyVAL.str = yyDollar[1].str
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:254
		{
			yyVAL.str = yyDollar[1].str
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:255
		{
			yyVAL.str = yyDollar[1].str
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:256
		{
			yyVAL.str = yyDollar[1].str
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:257
		{
			yyVAL.str = yyDollar[1].str
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:258
		{
			yyVAL.str = yyDollar[1].str
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:259
		{
			yyVAL.str = yyDollar[1].str
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:260
		{
			yyVAL.str = yyDollar[1].str
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:261
		{
			yyVAL.str = yyDollar[1].str
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:262
		{
			yyVAL.str = yyDollar[1].str
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:263
		{
			yyVAL.str = yyDollar[1].str
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:264
		{
			yyVAL.str = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:265
		{
			yyVAL.str = yyDollar[1].str
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:266
		{
			yyVAL.str = yyDollar[1].str
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:267
		{
			yyVAL.str = yyDollar[1].str
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:268
		{
			yyVAL.str = yyDollar[1].str
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:269
		{
			yyVAL.str = yyDollar[1].str
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:270
		{
			yyVAL.str = yyDollar[1].str
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:271
		{
			yyVAL.str = yyDollar[1].str
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:272
		{
			yyVAL.str = yyDollar[1].str
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:273
		{
			yyVAL.str = yyDollar[1].str
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:274
		{
			yyVAL.str = yyDollar[1].str
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:275
		{
			yyVAL.str = yyDollar[1].str
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:276
		{
			yyVAL.str = yyDollar[1].str
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:277
		{
			yyVAL.str = yyDollar[1].str
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:278
		{
			yyVAL.str = yyDollar[1].str
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:279
		{
			yyVAL.str = yyDollar[1].str
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:280
		{
			yyVAL.str = yyDollar[1].str
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:281
		{
			yyVAL.str = yyDollar[1].str
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:282
		{
			yyVAL.str = yyDollar[1].str
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:283
		{
			yyVAL.str = yyDollar[1].str
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:284
		{
			yyVAL.str = yyDollar[1].str
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:285
		{
			yyVAL.str = yyDollar[1].str
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:286
		{
			yyVAL.str = yyDollar[1].str
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:287
		{
			yyVAL.str = yyDollar[1].str
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:288
		{
			yyVAL.str = yyDollar[1].str
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:289
		{
			yyVAL.str = yyDollar[1].str
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:290
		{
			yyVAL.str = yyDollar[1].str
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:291
		{
			yyVAL.str = yyDollar[1].str
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:292
		{
			yyVAL.str = yyDollar[1].str
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:293
		{
			yyVAL.str = yyDollar[1].str
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:294
		{
			yyVAL.str = yyDollar[1].str
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:295
		{
			yyVAL.str = yyDollar[1].str
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:296
		{
			yyVAL.str = yyDollar[1].str
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:297
		{
			yyVAL.str = yyDollar[1].str
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:298
		{
			yyVAL.str = yyDollar[1].str
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:299
		{
			yyVAL.str = yyDollar[1].str
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:300
		{
			yyVAL.str = yyDollar[1].str
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:301
		{
			yyVAL.str = yyDollar[1].str
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:302
		{
			yyVAL.str = yyDollar[1].str
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:303
		{
			yyVAL.str = yyDollar[1].str
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:304
		{
			yyVAL.str = yyDollar[1].str
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:305
		{
			yyVAL.str = yyDollar[1].str
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:306
		{
			yyVAL.str = yyDollar[1].str
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:307
		{
			yyVAL.str = yyDollar[1].str
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:308
		{
			yyVAL.str = yyDollar[1].str
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:309
		{
			yyVAL.str = yyDollar[1].str
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:310
		{
			yyVAL.str = yyDollar[1].str
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:311
		{
			yyVAL.str = yyDollar[1].str
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:314
		{
			yyVAL.str = yyDollar[1].str
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:314
		{
			yyVAL.str = yyDollar[1].str
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:314
		{
			yyVAL.str = yyDollar[1].str
		}
	case 74:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:318
		{
		}
	case 75:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:319
		{
		}
	case 76:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:325
		{
			yyVAL.statement = nil
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:327
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:329
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:331
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:333
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:335
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:337
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:339
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:341
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:343
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:345
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:347
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:349
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:351
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:353
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:359
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:364
		{
			yyVAL.str = yyDollar[1].str
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:368
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:374
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:379
		{
			yyVAL.str = yyDollar[1].str
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:381
		{
			yyVAL.str = "AND"
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:383
		{
			yyVAL.str = "OR"
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:385
		{
			yyVAL.str = "!="
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:387
		{
			yyVAL.str = "="
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:389
		{
			yyVAL.str = "<"
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:391
		{
			yyVAL.str = ">"
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:393
		{
			yyVAL.str = ">="
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:395
		{
			yyVAL.str = "<="
		}
	case 104:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:397
		{
			yyVAL.str = yyDollar[1].str
		}
	case 105:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:424
		{
		}
	case 106:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:424
		{
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:426
		{
		}
	case 108:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:429
		{
			yyVAL.str = ""
		}
	case 109:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:433
		{
			yyVAL.str = ""
		}
	case 111:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:441
		{
			yyVAL.aexpr = &AExprLeaf{
				Value: yyDollar[1].str,
			}
		}
	case 112:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:446
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:449
		{
		}
	case 114:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:452
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 115:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:482
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 116:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:484
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:486
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:494
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:502
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:510
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:518
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:526
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:534
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:542
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:550
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:558
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:566
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 128:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:574
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:583
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:596
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 131:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:604
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 132:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:612
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 133:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:722
		{
			yyVAL.aexpr = 1
		}
	case 134:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:724
		{
			yyVAL.aexpr = 1
		}
	case 135:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:726
		{
			yyVAL.aexpr = 1
		}
	case 136:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:728
		{
			yyVAL.aexpr = 1
		}
	case 137:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:747
		{
			yyVAL.aexpr = 1
		}
	case 138:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:749
		{
			yyVAL.aexpr = 1
		}
	case 139:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:751
		{
			yyVAL.aexpr = 1
		}
	case 140:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:753
		{
			yyVAL.aexpr = 1
		}
	case 141:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:773
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[5].aexpr,
				Op:    yyDollar[3].str,
			}
		}
	case 142:
		yyDollar = yyS[yypt-6 : yypt+1]
//line lyx/gram.y:781
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[6].aexpr,
				Op:    yyDollar[3].str,
			}
		}
	case 143:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:900
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 144:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:902
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 145:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:904
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 146:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:908
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 147:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:918
		{
			/*
			 * The SQL spec only allows DEFAULT in "contextually typed
			 * expressions", but for us, it's easier to allow it in
			 * any a_expr and then throw error during parse analysis
			 * if it's in an inappropriate context.  This way also
			 * lets us say something smarter than "syntax error".
			 */

		}
	case 148:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:932
		{
			yyVAL.colref = ColumnRef{
				ColName:    yyDollar[3].str,
				TableAlias: yyDollar[1].str,
			}
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:940
		{
			yyVAL.colref = ColumnRef{
				ColName: yyDollar[1].str,
			}
		}
	case 150:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:944
		{
			yyVAL.colref = yyDollar[1].colref
		}
	case 151:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:952
		{ /* result not matter */
		}
	case 152:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:954
		{ /* result not matter */
		}
	case 153:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:956
		{ /* result not matter */
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:958
		{ /* result not matter */
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:960
		{ /* result not matter */
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:962
		{ /* result not matter */
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:964
		{ /* result not matter */
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:966
		{ /* result not matter */
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:968
		{ /* result not matter */
		}
	case 160:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:970
		{ /* result not matter */
		}
	case 161:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:972
		{ /* result not matter */
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:974
		{ /* result not matter */
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:976
		{ /* result not matter */
		}
	case 164:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:978
		{ /* result not matter */
		}
	case 165:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:979
		{ /* result not matter */
		}
	case 166:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:984
		{
			yyVAL.aexpr = &AExprEmpty{}
		}
	case 167:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:988
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 168:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:993
		{
		}
	case 169:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:994
		{
		}
	case 170:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:998
		{
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:999
		{
		}
	case 172:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1003
		{

		}
	case 173:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1007
		{

		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1011
		{

		}
	case 175:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1015
		{

		}
	case 176:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1022
		{
			yyVAL.statement = &VarSet{
				Name:  yyDollar[2].str,
				Value: yyDollar[4].str,
			}
		}
	case 177:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1028
		{
			yyVAL.statement = &VarSet{
				IsLocal: true,
				Name:    yyDollar[3].str,
				Value:   yyDollar[5].str,
			}
		}
	case 178:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1035
		{
		}
	case 179:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1036
		{
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1041
		{
			yyVAL.statement = &Begin{}
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1050
		{
			yyVAL.statement = &Commit{}
		}
	case 182:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1059
		{
			yyVAL.statement = &Rollback{}
		}
	case 183:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1067
		{
			yyVAL.statement = &Execute{
				Id: yyDollar[2].str,
			}
		}
	case 184:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1075
		{
			yyVAL.statement = &Execute{
				Id: yyDollar[2].str,
			}
		}
	case 185:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1082
		{
			yyVAL.statement = yyDollar[1].selectStmt
		}
	case 186:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1084
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 187:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1086
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 188:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1088
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 189:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1090
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 190:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1092
		{
			yyVAL.statement = &Explain{
				Stmt: yyDollar[2].statement,
			}
		}
	case 191:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1099
		{
		}
	case 192:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1100
		{
		}
	case 193:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1103
		{
		}
	case 194:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1104
		{
		}
	case 195:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1107
		{
			yyVAL.tableelt = []TableElt{{
				ColName: yyDollar[1].str,
				ColType: yyDollar[2].str,
			},
			}
		}
	case 196:
		yyDollar = yyS[yypt-6 : yypt+1]
//line lyx/gram.y:1114
		{
			yyVAL.tableelt = nil
		}
	case 197:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1117
		{
			yyVAL.tableelt = append(yyDollar[1].tableelt, yyDollar[3].tableelt...)
		}
	case 198:
		yyDollar = yyS[yypt-7 : yypt+1]
//line lyx/gram.y:1122
		{
			yyVAL.statement = &CreateTable{
				TableName: yyDollar[3].str,
				TableElts: yyDollar[5].tableelt,
			}
		}
	case 199:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1127
		{
			yyVAL.statement = &Index{}
		}
	case 200:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1131
		{
			yyVAL.statement = &CreateRole{}
		}
	case 201:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1135
		{
			yyVAL.statement = &CreateDatabase{}
		}
	case 202:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1142
		{
			yyVAL.statement = &Alter{}
		}
	case 203:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1149
		{
			yyVAL.statement = &Vacuum{}
		}
	case 204:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1156
		{
			yyVAL.statement = &Cluster{}
		}
	case 205:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1164
		{
			yyVAL.statement = &Analyze{}
		}
	case 206:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1171
		{
			yyVAL.statement = &Drop{}
		}
	case 207:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1179
		{
			yyVAL.statement = &Truncate{}
		}
	case 208:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1186
		{
		}
	case 209:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1186
		{
		}
	case 210:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1187
		{
		}
	case 211:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1187
		{
		}
	case 212:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1188
		{
		}
	case 213:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1188
		{
		}
	case 214:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1189
		{
		}
	case 215:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1189
		{
		}
	case 216:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1190
		{
		}
	case 217:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1190
		{
		}
	case 218:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1191
		{
		}
	case 219:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1191
		{
		}
	case 220:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1192
		{
		}
	case 221:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1192
		{
		}
	case 222:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1198
		{
			yyVAL.from_list = yyDollar[2].from_list
		}
	case 223:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1199
		{
		}
	case 224:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1203
		{
			yyVAL.from_list = []FromClauseNode{yyDollar[1].from}
		}
	case 225:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1204
		{
			yyVAL.from_list = append(yyDollar[1].from_list, yyDollar[3].from)
		}
	case 226:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1208
		{
			yyVAL.tableref = &RangeVar{
				SchemaName:   "",
				RelationName: yyDollar[1].str,
				Alias:        "",
			}
		}
	case 227:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1215
		{
			yyVAL.tableref = &RangeVar{
				SchemaName:   yyDollar[1].str,
				RelationName: yyDollar[3].str,
				Alias:        "",
			}
		}
	case 228:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1225
		{
			yyVAL.str = yyDollar[2].str
		}
	case 229:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1229
		{
			yyVAL.str = yyDollar[1].str
		}
	case 230:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1235
		{
			yyVAL.str = ""
		}
	case 232:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1243
		{
			yyDollar[1].tableref.SetAlias(yyDollar[2].str)
			yyVAL.from = yyDollar[1].tableref
		}
	case 233:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1248
		{
			yyVAL.from = yyDollar[1].tableref
		}
	case 234:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1252
		{
			yyDollar[2].tableref.SetAlias(yyDollar[4].str)
			yyVAL.from = yyDollar[2].tableref
		}
	case 235:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1260
		{
		}
	case 236:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1261
		{
		}
	case 237:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1265
		{
		}
	case 238:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1266
		{
		}
	case 239:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1267
		{
		}
	case 240:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1268
		{
		}
	case 241:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1279
		{

		}
	case 242:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1287
		{
			yyVAL.tableref = yyDollar[2].tableref
		}
	case 243:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1291
		{
			/* CROSS JOIN is same as unqualified inner join */
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[4].from,
			}
		}
	case 244:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1299
		{
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[4].from,
			}
		}
	case 245:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1306
		{
			/* letting join_type reduce to empty doesn't work */
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[3].from,
			}
		}
	case 246:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1314
		{
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[5].from,
			}
		}
	case 247:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1321
		{
			/* letting join_type reduce to empty doesn't work */
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[4].from,
			}
		}
	case 248:
		yyDollar = yyS[yypt-11 : yypt+1]
//line lyx/gram.y:1336
		{
			yyVAL.selectStmt = &Select{
				FromClause: yyDollar[3].from_list,
				Where:      yyDollar[4].aexpr,
			}
		}
	case 249:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1341
		{
			yyVAL.selectStmt = &Select{}
		}
	case 250:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1348
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 251:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1349
		{
			yyVAL.strlist = append(yyDollar[3].strlist, yyDollar[1].str)
		}
	case 252:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1354
		{
		}
	case 253:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1354
		{
		}
	case 254:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1357
		{
			yyVAL.strlist = yyDollar[2].strlist
		}
	case 255:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1363
		{
		}
	case 256:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1364
		{
		}
	case 257:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1369
		{
			yyVAL.aexprList = []AExpr{yyDollar[1].aexpr}
		}
	case 258:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1371
		{
			yyVAL.aexprList = append(yyDollar[3].aexprList, yyDollar[1].aexpr)
		}
	case 259:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1376
		{
			yyVAL.aexprList = yyDollar[2].aexprList
		}
	case 260:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1382
		{
		}
	case 261:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1383
		{
		}
	case 262:
		yyDollar = yyS[yypt-7 : yypt+1]
//line lyx/gram.y:1389
		{
			yyVAL.statement = &Insert{
				TableRef: yyDollar[3].tableref,
				Columns:  yyDollar[4].strlist,
				Values:   yyDollar[6].aexprList,
			}
		}
	case 263:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1395
		{
			yyVAL.statement = &Insert{
				TableRef:  yyDollar[3].tableref,
				SubSelect: yyDollar[5].selectStmt,
			}
		}
	case 264:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1403
		{
		}
	case 265:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1404
		{
		}
	case 266:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1407
		{
		}
	case 267:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1408
		{
		}
	case 268:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1414
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 269:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1415
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 270:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1420
		{
			yyVAL.str = yyDollar[1].str
		}
	case 271:
		yyDollar = yyS[yypt-8 : yypt+1]
//line lyx/gram.y:1430
		{
			yyVAL.statement = &Update{
				TableRef: yyDollar[3].tableref,
				Where:    yyDollar[7].aexpr,
			}
		}
	case 272:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1441
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 273:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1442
		{
			yyVAL.strlist = append(yyDollar[3].strlist, yyDollar[1].str)
		}
	case 274:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1447
		{
		}
	case 275:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1448
		{
		}
	case 276:
		yyDollar = yyS[yypt-7 : yypt+1]
//line lyx/gram.y:1452
		{
			yyVAL.statement = &Delete{
				TableRef: yyDollar[4].tableref,
				Where:    yyDollar[6].aexpr,
			}
		}
	case 277:
		yyDollar = yyS[yypt-6 : yypt+1]
//line lyx/gram.y:1461
		{
			yyVAL.statement = &Copy{
				TableRef: yyDollar[2].tableref,
				Where:    yyDollar[6].aexpr,
				IsFrom:   false,
			}
		}
	}
	goto yystack /* stack new state and value */
}
