// Code generated by goyacc -o lyx/gram.go -p yy lyx/gram.y. DO NOT EDIT.

//line lyx/gram.y:3
package routerparser

import __yyfmt__ "fmt"

//line lyx/gram.y:3

import (
	"crypto/rand"
	"encoding/hex"
)

func randomHex(n int) (string, error) {
	bytes := make([]byte, n)
	if _, err := rand.Read(bytes); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes), nil
}

//line lyx/gram.y:21
type yySymType struct {
	yys     int
	str     string
	strlist []string
	byte    byte
	bytes   []byte
	int     int
	bool    bool
	empty   struct{}

	statement Statement
	from_list []FromClauseNode
	from      FromClauseNode
	tableelt  []TableElt
	tableref  FromClauseNode

	selectStmt *Select

	colref ColumnRef

	aexpr AExpr

	aexprList []AExpr
}

const STRING = 57346
const CREATE = 57347
const ALTER = 57348
const ROLE = 57349
const DATABASE = 57350
const NATURAL = 57351
const TABLE = 57352
const INDEX = 57353
const SELECT = 57354
const UPDATE = 57355
const INSERT = 57356
const DELETE = 57357
const FROM = 57358
const WHERE = 57359
const AND = 57360
const VALUES = 57361
const OR = 57362
const EXPLAIN = 57363
const EXECUTE = 57364
const PREPARE = 57365
const BEGIN = 57366
const COMMIT = 57367
const ROLLBACK = 57368
const VACUUM = 57369
const CLUSTER = 57370
const ANALYZE = 57371
const INTO = 57372
const OUTER_P = 57373
const FULL = 57374
const RIGHT = 57375
const LEFT = 57376
const INNER_P = 57377
const DROP = 57378
const TRUNCATE = 57379
const FETCH = 57380
const FOR = 57381
const ORDER = 57382
const GROUP = 57383
const BY = 57384
const OFFSET = 57385
const LIMIT = 57386
const WINDOW = 57387
const CROSS = 57388
const SET = 57389
const RESET = 57390
const LOCAL = 57391
const ALL = 57392
const PRIMARY = 57393
const KEY = 57394
const FOREIGN = 57395
const REFERENCES = 57396
const USING = 57397
const TCOLON = 57398
const TCOMMA = 57399
const TOPENBR = 57400
const TCLOSEBR = 57401
const TSEMICOLON = 57402
const TNOT_EQUALS = 57403
const TDOT = 57404
const NULL_P = 57405
const ISNULL = 57406
const ON = 57407
const JOIN = 57408
const TPLUS = 57409
const TMINUS = 57410
const TMUL = 57411
const TDIV = 57412
const TGREATER = 57413
const TGREATER_EQUALS = 57414
const TLESS = 57415
const TLESS_EQUALS = 57416
const TMOD = 57417
const TPOW = 57418
const FALSE_P = 57419
const TRUE_P = 57420
const TEQ = 57421
const OP = 57422
const ONLY = 57423
const RETURNING = 57424
const COPY = 57425
const IS = 57426
const NOT = 57427
const NULL = 57428
const DISTINCT = 57429
const DEFAULT = 57430
const NORMALIZED = 57431
const NOTNULL = 57432
const DOCUMENT_P = 57433
const TO = 57434
const STDOUT = 57435
const AS = 57436

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING",
	"CREATE",
	"ALTER",
	"ROLE",
	"DATABASE",
	"NATURAL",
	"TABLE",
	"INDEX",
	"SELECT",
	"UPDATE",
	"INSERT",
	"DELETE",
	"FROM",
	"WHERE",
	"AND",
	"VALUES",
	"OR",
	"EXPLAIN",
	"EXECUTE",
	"PREPARE",
	"BEGIN",
	"COMMIT",
	"ROLLBACK",
	"VACUUM",
	"CLUSTER",
	"ANALYZE",
	"INTO",
	"OUTER_P",
	"FULL",
	"RIGHT",
	"LEFT",
	"INNER_P",
	"DROP",
	"TRUNCATE",
	"FETCH",
	"FOR",
	"ORDER",
	"GROUP",
	"BY",
	"OFFSET",
	"LIMIT",
	"WINDOW",
	"CROSS",
	"SET",
	"RESET",
	"LOCAL",
	"ALL",
	"PRIMARY",
	"KEY",
	"FOREIGN",
	"REFERENCES",
	"USING",
	"TCOLON",
	"TCOMMA",
	"TOPENBR",
	"TCLOSEBR",
	"TSEMICOLON",
	"TNOT_EQUALS",
	"TDOT",
	"NULL_P",
	"ISNULL",
	"ON",
	"JOIN",
	"TPLUS",
	"TMINUS",
	"TMUL",
	"TDIV",
	"TGREATER",
	"TGREATER_EQUALS",
	"TLESS",
	"TLESS_EQUALS",
	"TMOD",
	"TPOW",
	"FALSE_P",
	"TRUE_P",
	"TEQ",
	"OP",
	"ONLY",
	"RETURNING",
	"COPY",
	"IS",
	"NOT",
	"NULL",
	"DISTINCT",
	"DEFAULT",
	"NORMALIZED",
	"NOTNULL",
	"DOCUMENT_P",
	"TO",
	"STDOUT",
	"AS",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line lyx/gram.y:1465

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 149,
	58, 90,
	-2, 72,
	-1, 240,
	18, 43,
	20, 43,
	59, 43,
	61, 43,
	64, 43,
	67, 43,
	68, 43,
	69, 43,
	70, 43,
	71, 43,
	72, 43,
	73, 43,
	74, 43,
	75, 43,
	76, 43,
	79, 43,
	80, 43,
	84, 43,
	90, 43,
	-2, 104,
}

const yyPrivate = 57344

const yyLast = 1034

var yyAct = [...]int{

	151, 341, 320, 347, 334, 209, 163, 285, 268, 304,
	252, 203, 59, 260, 146, 17, 213, 200, 138, 153,
	289, 248, 348, 154, 214, 212, 318, 50, 52, 54,
	56, 206, 51, 159, 263, 265, 264, 266, 336, 300,
	299, 51, 157, 57, 202, 58, 58, 58, 58, 58,
	291, 58, 292, 139, 160, 184, 43, 185, 156, 381,
	363, 37, 39, 38, 40, 58, 358, 231, 303, 51,
	22, 58, 314, 58, 309, 128, 129, 130, 131, 280,
	136, 234, 233, 378, 327, 317, 288, 313, 245, 232,
	207, 235, 195, 237, 158, 236, 170, 291, 182, 349,
	161, 187, 162, 258, 171, 172, 173, 174, 178, 181,
	177, 180, 175, 176, 249, 273, 179, 183, 370, 51,
	350, 186, 269, 215, 294, 326, 315, 188, 51, 275,
	274, 189, 41, 246, 296, 51, 262, 168, 353, 276,
	190, 278, 365, 277, 354, 297, 256, 329, 58, 58,
	58, 376, 372, 157, 157, 281, 305, 201, 152, 263,
	265, 264, 266, 42, 210, 3, 310, 279, 254, 196,
	197, 157, 204, 259, 55, 198, 155, 165, 166, 167,
	53, 44, 45, 46, 47, 48, 262, 208, 49, 51,
	238, 37, 335, 261, 164, 316, 191, 192, 193, 157,
	199, 194, 369, 250, 325, 148, 150, 1, 253, 263,
	265, 264, 266, 375, 270, 247, 157, 371, 251, 204,
	364, 352, 328, 259, 295, 216, 217, 218, 219, 220,
	221, 222, 223, 224, 225, 226, 227, 228, 229, 230,
	271, 272, 255, 261, 267, 284, 201, 286, 287, 242,
	201, 134, 135, 244, 132, 133, 312, 243, 21, 157,
	282, 14, 157, 283, 257, 293, 204, 290, 13, 12,
	308, 11, 10, 16, 306, 307, 302, 15, 6, 5,
	4, 9, 8, 20, 298, 19, 18, 301, 7, 321,
	141, 241, 253, 319, 137, 322, 211, 169, 2, 0,
	157, 157, 323, 0, 157, 0, 0, 58, 0, 0,
	270, 58, 58, 0, 0, 0, 286, 0, 338, 0,
	0, 0, 344, 343, 345, 332, 333, 58, 351, 337,
	0, 0, 0, 311, 0, 0, 324, 157, 355, 0,
	330, 331, 0, 0, 0, 0, 0, 0, 360, 0,
	321, 0, 362, 0, 0, 0, 340, 0, 0, 0,
	0, 368, 357, 58, 339, 0, 0, 342, 58, 58,
	0, 374, 346, 0, 0, 0, 0, 0, 0, 380,
	58, 0, 0, 0, 0, 0, 0, 58, 0, 356,
	0, 58, 361, 0, 0, 0, 0, 366, 367, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 373,
	0, 0, 0, 342, 0, 0, 377, 0, 0, 0,
	379, 149, 81, 82, 89, 90, 0, 70, 88, 61,
	62, 63, 64, 65, 66, 67, 69, 68, 71, 72,
	73, 74, 75, 76, 83, 84, 85, 94, 0, 0,
	0, 0, 0, 86, 87, 98, 97, 91, 92, 93,
	96, 95, 0, 117, 77, 78, 79, 80, 109, 107,
	108, 110, 0, 102, 101, 147, 100, 104, 126, 0,
	0, 0, 121, 116, 142, 143, 111, 115, 124, 125,
	122, 123, 113, 114, 120, 119, 0, 127, 103, 106,
	0, 118, 144, 0, 0, 145, 149, 81, 82, 89,
	90, 105, 70, 88, 61, 62, 63, 64, 65, 66,
	67, 69, 68, 71, 72, 73, 74, 75, 76, 83,
	84, 85, 94, 0, 0, 0, 0, 0, 86, 87,
	98, 97, 91, 92, 93, 96, 95, 0, 117, 77,
	78, 79, 80, 109, 107, 108, 110, 0, 102, 101,
	147, 240, 104, 126, 0, 0, 0, 121, 116, 142,
	143, 111, 115, 124, 125, 122, 123, 113, 114, 120,
	119, 0, 127, 103, 106, 0, 118, 144, 0, 0,
	145, 149, 81, 82, 89, 90, 105, 70, 88, 61,
	62, 63, 64, 65, 66, 67, 69, 68, 71, 72,
	73, 74, 75, 76, 83, 84, 85, 94, 0, 0,
	0, 0, 0, 86, 87, 98, 97, 91, 92, 93,
	96, 95, 0, 117, 77, 78, 79, 80, 109, 107,
	108, 110, 0, 102, 101, 147, 100, 104, 126, 0,
	0, 0, 121, 116, 142, 143, 140, 115, 124, 125,
	122, 123, 113, 114, 120, 119, 0, 127, 103, 106,
	0, 118, 144, 0, 0, 145, 60, 81, 82, 89,
	90, 105, 70, 88, 61, 62, 63, 64, 65, 66,
	67, 69, 68, 71, 72, 73, 74, 75, 76, 83,
	84, 85, 94, 0, 0, 0, 0, 0, 86, 87,
	98, 97, 91, 92, 93, 96, 95, 0, 117, 77,
	78, 79, 80, 109, 107, 108, 110, 0, 102, 101,
	99, 100, 104, 126, 0, 0, 0, 121, 116, 112,
	0, 111, 115, 124, 125, 122, 123, 113, 114, 120,
	119, 0, 127, 103, 106, 0, 118, 0, 0, 0,
	0, 205, 81, 82, 89, 90, 105, 70, 88, 61,
	62, 63, 64, 65, 66, 67, 69, 68, 71, 72,
	73, 74, 75, 76, 83, 84, 85, 94, 0, 0,
	0, 0, 0, 86, 87, 98, 97, 91, 92, 93,
	96, 95, 0, 117, 77, 78, 79, 80, 109, 107,
	108, 110, 0, 102, 101, 99, 100, 104, 126, 184,
	0, 185, 121, 116, 112, 0, 111, 115, 124, 125,
	122, 123, 113, 114, 120, 119, 0, 127, 103, 106,
	0, 118, 0, 184, 0, 185, 0, 0, 0, 0,
	0, 105, 0, 0, 0, 0, 0, 0, 359, 0,
	0, 0, 182, 0, 0, 187, 0, 0, 171, 172,
	173, 174, 178, 181, 177, 180, 175, 176, 0, 0,
	179, 183, 0, 0, 239, 186, 182, 0, 184, 187,
	185, 188, 171, 172, 173, 174, 178, 181, 177, 180,
	175, 176, 0, 0, 179, 183, 0, 0, 0, 186,
	0, 0, 0, 0, 0, 188, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 182, 0, 0, 187, 0, 0, 171, 172, 173,
	174, 178, 181, 177, 180, 175, 176, 0, 0, 179,
	183, 0, 0, 0, 186, 35, 36, 0, 0, 0,
	188, 0, 37, 39, 38, 40, 0, 0, 0, 0,
	0, 22, 26, 29, 23, 24, 25, 30, 31, 32,
	0, 0, 0, 0, 0, 0, 34, 33, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 27, 28, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 41,
}
var yyPact = [...]int{

	950, -1000, -4, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -4, -4, -4,
	-4, -4, 49, -1000, -1000, -1000, 185, 131, 124, 185,
	672, 672, 672, 672, 672, 244, 672, 587, 128, -58,
	160, 185, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	672, -1000, -46, 185, -1000, -1000, 672, -1000, 672, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 190, 672, 672, 672, -1000, 80, -1000, 37,
	-1000, -1000, 417, 417, 417, -1000, -1000, 417, -1000, -1000,
	-1000, 34, 185, 185, -1000, -58, 185, -18, -1000, 757,
	-48, -1000, -1000, 32, -1000, -1000, -1000, -1000, 587, 147,
	65, 417, 417, 417, 417, 417, 417, 417, 417, 417,
	417, 417, 417, 417, 417, 417, 4, -1000, -1000, 185,
	-1000, 870, 870, 870, 825, 502, 30, 86, 185, -71,
	-1000, 57, 185, -1000, -1000, -1000, 757, 115, -1000, 105,
	417, 46, 177, 28, -1000, 65, 870, 870, 870, 870,
	870, 870, 870, 870, 870, 870, 870, 870, 870, 870,
	870, -1000, 52, -1000, -1000, 151, -1000, -1000, -1000, -1000,
	-1000, 20, 870, 136, 179, 185, 185, 31, -73, 185,
	-1000, -1000, -7, 757, 72, 89, 103, 870, 65, -26,
	-27, 65, 2, 125, 125, 125, -1000, -1000, -1000, 185,
	-1000, 15, 177, -1000, -1000, -1000, 150, -1000, -1000, 417,
	-1000, 29, -1000, 13, 69, -1000, -53, 147, 185, 147,
	-1000, 115, 672, 74, 26, 107, 672, 672, 177, 65,
	65, 127, -28, 65, -1000, -1000, -1000, -1000, -1000, 28,
	417, 870, 672, 417, -1000, 185, 147, 190, 417, -60,
	-1000, 42, -1000, 40, -1000, -1000, 68, 185, 94, 102,
	-1000, -1000, 177, 127, -1000, 417, 65, 177, -1000, 870,
	-1000, 7, 801, -1000, -60, -1000, 870, -1000, 672, 185,
	-1000, 1, 99, 672, 672, -1000, 870, 177, -1000, 417,
	-1000, -1000, -1000, 64, 114, 672, -1000, -1000, -1000, -1000,
	185, 112, 672, -1000, 25, -1000, 672, -1000, 185, -1000,
	0, -1000,
}
var yyPgo = [...]int{

	0, 298, 165, 0, 11, 6, 5, 297, 296, 25,
	16, 24, 294, 294, 291, 53, 290, 290, 12, 288,
	15, 286, 285, 283, 282, 281, 280, 279, 278, 277,
	273, 272, 271, 269, 268, 261, 163, 258, 258, 258,
	17, 257, 1, 256, 253, 14, 248, 2, 245, 10,
	19, 244, 8, 43, 7, 244, 242, 224, 222, 221,
	220, 217, 213, 207, 206, 205, 205, 18, 204, 202,
	9, 13, 4, 200, 3, 195,
}
var yyR1 = [...]int{

	0, 63, 36, 36, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 45, 45, 53, 53, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 4, 4, 5, 55, 55, 55, 55, 55, 55,
	55, 55, 55, 55, 64, 64, 14, 13, 13, 65,
	16, 16, 16, 15, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 39, 38, 38,
	17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
	17, 17, 17, 17, 17, 6, 6, 66, 66, 12,
	12, 67, 67, 67, 67, 24, 24, 24, 24, 26,
	27, 28, 19, 25, 2, 2, 2, 2, 2, 2,
	68, 68, 69, 69, 49, 49, 49, 29, 29, 29,
	29, 30, 31, 32, 33, 35, 34, 56, 56, 57,
	57, 58, 58, 59, 59, 60, 60, 61, 61, 62,
	62, 7, 7, 8, 8, 10, 10, 52, 52, 51,
	51, 9, 9, 9, 70, 70, 71, 71, 71, 71,
	72, 11, 11, 11, 11, 11, 11, 20, 20, 40,
	40, 73, 73, 41, 44, 44, 42, 42, 43, 74,
	74, 21, 21, 50, 50, 75, 75, 48, 48, 54,
	22, 47, 47, 46, 46, 23, 37,
}
var yyR2 = [...]int{

	0, 2, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 0, 2, 0, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 3, 4, 1, 1, 3, 1,
	1, 3, 1, 1, 2, 2, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 3, 2, 4, 2, 3, 4, 3, 4,
	5, 6, 3, 4, 3, 4, 1, 3, 1, 1,
	2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 1, 0, 2, 1, 0, 1,
	3, 3, 2, 1, 1, 4, 5, 2, 2, 1,
	1, 1, 3, 3, 2, 2, 2, 2, 2, 2,
	0, 2, 0, 5, 3, 6, 3, 7, 3, 3,
	3, 2, 2, 2, 2, 2, 2, 0, 3, 0,
	2, 0, 3, 0, 2, 0, 2, 0, 2, 0,
	2, 2, 0, 1, 3, 1, 3, 2, 1, 0,
	1, 2, 1, 4, 1, 0, 2, 2, 2, 1,
	2, 3, 4, 5, 4, 5, 4, 11, 2, 1,
	3, 0, 1, 3, 0, 1, 1, 3, 3, 0,
	2, 7, 5, 0, 1, 0, 2, 1, 3, 3,
	8, 1, 3, 0, 2, 7, 6,
}
var yyChk = [...]int{

	-1000, -63, -1, -2, -26, -27, -28, -19, -24, -25,
	-31, -32, -33, -34, -35, -29, -30, -20, -21, -22,
	-23, -37, 21, 24, 25, 26, 22, 47, 48, 23,
	27, 28, 29, 37, 36, 5, 6, 12, 14, 13,
	15, 83, -36, 60, -36, -36, -36, -36, -36, -2,
	-3, 4, -3, 49, -3, 50, -3, -53, -45, -18,
	4, 12, 13, 14, 15, 16, 17, 18, 20, 19,
	10, 21, 22, 23, 24, 25, 26, 47, 48, 49,
	50, 5, 6, 27, 28, 29, 36, 37, 11, 7,
	8, 40, 41, 42, 30, 44, 43, 39, 38, 58,
	59, 57, 56, 81, 60, 94, 82, 52, 53, 51,
	54, 69, 67, 75, 76, 70, 66, 46, 84, 78,
	77, 65, 73, 74, 71, 72, 61, 80, -53, -53,
	-53, -53, 10, 11, 7, 8, -53, -12, -67, -15,
	69, -16, 67, 68, 85, 88, -45, 58, -65, 4,
	-64, -3, 30, -50, 81, 16, -10, -3, -53, 79,
	-3, -53, -53, -5, 4, -53, -53, -53, 57, -7,
	16, 67, 68, 69, 70, 75, 76, 73, 71, 79,
	74, 72, 61, 80, 18, 20, 84, 64, 90, 94,
	-3, -15, -15, -15, -15, 58, -10, -10, -50, -73,
	-40, -3, 62, -4, -18, 4, 79, 58, -67, -6,
	17, -8, -9, -10, -11, 58, -15, -15, -15, -15,
	-15, -15, -15, -15, -15, -15, -15, -15, -15, -15,
	-15, 63, 85, 78, 77, 87, 91, 89, -3, 59,
	59, -14, -15, -41, -44, 58, 47, -10, 92, 57,
	-3, -4, -49, -3, 53, -56, 41, -15, 57, 46,
	-71, 66, 9, 32, 34, 33, 35, -51, -52, 94,
	-3, -11, -9, 63, 78, 77, 87, 91, 89, 16,
	59, 19, -20, -40, -48, -54, -3, -46, 55, 93,
	-40, 57, 59, -4, 52, -57, 45, 42, -9, 66,
	66, -9, -71, 66, -70, 31, -70, -70, -3, 59,
	16, -15, -43, 58, 59, 57, -75, 16, 79, -6,
	-47, -3, -6, -49, -53, -68, 51, 58, -58, 40,
	-53, -53, -9, -9, -72, 65, 66, -9, -52, -15,
	-53, -42, -15, -54, -6, -5, -15, -74, 82, 57,
	52, -3, -59, 44, 42, -72, -15, -9, 59, 57,
	-74, -53, -47, 59, -60, 43, -53, -53, -42, -69,
	54, -61, 38, -53, -3, -62, 39, -53, 58, -53,
	-3, 59,
}
var yyDef = [...]int{

	75, -2, 2, 76, 77, 78, 79, 80, 81, 82,
	83, 84, 85, 86, 87, 88, 89, 2, 2, 2,
	2, 2, 0, 179, 180, 181, 0, 0, 0, 0,
	73, 73, 73, 73, 73, 0, 73, 0, 0, 263,
	0, 0, 1, 3, 184, 185, 186, 187, 188, 189,
	73, 90, 0, 0, 177, 178, 73, 202, 73, 71,
	72, 4, 5, 6, 7, 8, 9, 10, 11, 12,
	13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
	43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
	53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
	63, 64, 65, 66, 67, 68, 69, 70, 203, 204,
	206, 205, 0, 73, 73, 73, 201, 222, 169, 173,
	54, 113, 55, 0, 0, 146, 110, 42, 112, -2,
	109, 0, 0, 0, 264, 263, 251, 225, 182, 0,
	0, 183, 74, 0, 93, 198, 199, 200, 0, 165,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 133, 135, 0,
	172, 114, 115, 131, 0, 0, 254, 0, 0, 0,
	252, 249, 0, 175, 91, 92, 0, 0, 170, 207,
	0, 221, 223, 229, 232, 0, 116, 117, 118, 119,
	120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
	130, 132, 0, 136, 138, 0, 142, 144, 171, 111,
	-2, 0, 106, 255, 0, 0, 0, 273, 0, 0,
	226, 176, 0, 0, 0, 209, 0, 166, 0, 0,
	0, 0, 0, 235, 235, 235, 239, 231, 230, 0,
	228, 232, 0, 134, 137, 139, 0, 143, 145, 0,
	105, 0, 262, 0, 265, 267, 0, 165, 0, 165,
	250, 0, 73, 190, 0, 211, 73, 73, 224, 0,
	0, 0, 0, 0, 236, 234, 237, 238, 227, 241,
	0, 140, 73, 0, 253, 0, 165, 0, 0, 259,
	274, 271, 276, 196, 197, 194, 0, 0, 213, 0,
	210, 208, 242, 0, 244, 0, 0, 246, 233, 141,
	261, 0, 256, 268, 259, 266, 269, 275, 73, 0,
	191, 0, 215, 73, 73, 243, 240, 245, 258, 0,
	270, 260, 272, 192, 217, 73, 214, 212, 257, 195,
	0, 219, 73, 216, 0, 247, 73, 218, 0, 220,
	0, 193,
}
var yyTok1 = [...]int{

	1,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:234
		{
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:235
		{

		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:241
		{
			yyVAL.str = yyDollar[1].str
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:242
		{
			yyVAL.str = yyDollar[1].str
		}
	case 6:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:243
		{
			yyVAL.str = yyDollar[1].str
		}
	case 7:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:244
		{
			yyVAL.str = yyDollar[1].str
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:245
		{
			yyVAL.str = yyDollar[1].str
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:246
		{
			yyVAL.str = yyDollar[1].str
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:247
		{
			yyVAL.str = yyDollar[1].str
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:248
		{
			yyVAL.str = yyDollar[1].str
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:249
		{
			yyVAL.str = yyDollar[1].str
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:250
		{
			yyVAL.str = yyDollar[1].str
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:251
		{
			yyVAL.str = yyDollar[1].str
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:252
		{
			yyVAL.str = yyDollar[1].str
		}
	case 16:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:253
		{
			yyVAL.str = yyDollar[1].str
		}
	case 17:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:254
		{
			yyVAL.str = yyDollar[1].str
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:255
		{
			yyVAL.str = yyDollar[1].str
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:256
		{
			yyVAL.str = yyDollar[1].str
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:257
		{
			yyVAL.str = yyDollar[1].str
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:258
		{
			yyVAL.str = yyDollar[1].str
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:259
		{
			yyVAL.str = yyDollar[1].str
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:260
		{
			yyVAL.str = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:261
		{
			yyVAL.str = yyDollar[1].str
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:262
		{
			yyVAL.str = yyDollar[1].str
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:263
		{
			yyVAL.str = yyDollar[1].str
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:264
		{
			yyVAL.str = yyDollar[1].str
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:265
		{
			yyVAL.str = yyDollar[1].str
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:266
		{
			yyVAL.str = yyDollar[1].str
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:267
		{
			yyVAL.str = yyDollar[1].str
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:268
		{
			yyVAL.str = yyDollar[1].str
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:269
		{
			yyVAL.str = yyDollar[1].str
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:270
		{
			yyVAL.str = yyDollar[1].str
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:271
		{
			yyVAL.str = yyDollar[1].str
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:272
		{
			yyVAL.str = yyDollar[1].str
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:273
		{
			yyVAL.str = yyDollar[1].str
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:274
		{
			yyVAL.str = yyDollar[1].str
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:275
		{
			yyVAL.str = yyDollar[1].str
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:276
		{
			yyVAL.str = yyDollar[1].str
		}
	case 40:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:277
		{
			yyVAL.str = yyDollar[1].str
		}
	case 41:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:278
		{
			yyVAL.str = yyDollar[1].str
		}
	case 42:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:279
		{
			yyVAL.str = yyDollar[1].str
		}
	case 43:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:280
		{
			yyVAL.str = yyDollar[1].str
		}
	case 44:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:281
		{
			yyVAL.str = yyDollar[1].str
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:282
		{
			yyVAL.str = yyDollar[1].str
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:283
		{
			yyVAL.str = yyDollar[1].str
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:284
		{
			yyVAL.str = yyDollar[1].str
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:285
		{
			yyVAL.str = yyDollar[1].str
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:286
		{
			yyVAL.str = yyDollar[1].str
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:287
		{
			yyVAL.str = yyDollar[1].str
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:288
		{
			yyVAL.str = yyDollar[1].str
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:289
		{
			yyVAL.str = yyDollar[1].str
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:290
		{
			yyVAL.str = yyDollar[1].str
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:291
		{
			yyVAL.str = yyDollar[1].str
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:292
		{
			yyVAL.str = yyDollar[1].str
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:293
		{
			yyVAL.str = yyDollar[1].str
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:294
		{
			yyVAL.str = yyDollar[1].str
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:295
		{
			yyVAL.str = yyDollar[1].str
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:296
		{
			yyVAL.str = yyDollar[1].str
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:297
		{
			yyVAL.str = yyDollar[1].str
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:298
		{
			yyVAL.str = yyDollar[1].str
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:299
		{
			yyVAL.str = yyDollar[1].str
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:300
		{
			yyVAL.str = yyDollar[1].str
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:301
		{
			yyVAL.str = yyDollar[1].str
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:302
		{
			yyVAL.str = yyDollar[1].str
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:303
		{
			yyVAL.str = yyDollar[1].str
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:304
		{
			yyVAL.str = yyDollar[1].str
		}
	case 68:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:305
		{
			yyVAL.str = yyDollar[1].str
		}
	case 69:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:306
		{
			yyVAL.str = yyDollar[1].str
		}
	case 70:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:307
		{
			yyVAL.str = yyDollar[1].str
		}
	case 71:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:310
		{
			yyVAL.str = yyDollar[1].str
		}
	case 72:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:310
		{
			yyVAL.str = yyDollar[1].str
		}
	case 73:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:314
		{
		}
	case 74:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:315
		{
		}
	case 75:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:321
		{
			yyVAL.statement = nil
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:323
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:325
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 78:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:327
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 79:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:329
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 80:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:331
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 81:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:333
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 82:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:335
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 83:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:337
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 84:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:339
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 85:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:341
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 86:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:343
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 87:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:345
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 88:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:347
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 89:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:349
		{
			setParseTree(yylex, yyDollar[1].statement)
		}
	case 90:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:355
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 91:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:360
		{
			yyVAL.str = yyDollar[1].str
		}
	case 92:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:364
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 93:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:370
		{
			yyVAL.str = string(yyDollar[1].str)
		}
	case 94:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:375
		{
			yyVAL.str = yyDollar[1].str
		}
	case 95:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:377
		{
			yyVAL.str = "AND"
		}
	case 96:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:379
		{
			yyVAL.str = "OR"
		}
	case 97:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:381
		{
			yyVAL.str = "!="
		}
	case 98:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:383
		{
			yyVAL.str = "="
		}
	case 99:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:385
		{
			yyVAL.str = "<"
		}
	case 100:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:387
		{
			yyVAL.str = ">"
		}
	case 101:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:389
		{
			yyVAL.str = ">="
		}
	case 102:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:391
		{
			yyVAL.str = "<="
		}
	case 103:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:393
		{
			yyVAL.str = yyDollar[1].str
		}
	case 104:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:420
		{
		}
	case 105:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:420
		{
		}
	case 106:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:422
		{
		}
	case 107:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:425
		{
			yyVAL.str = ""
		}
	case 108:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:429
		{
			yyVAL.str = ""
		}
	case 110:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:437
		{
			yyVAL.aexpr = &AExprLeaf{
				Value: yyDollar[1].str,
			}
		}
	case 111:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:442
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 112:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:445
		{
		}
	case 113:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:448
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 114:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:478
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 115:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:480
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 116:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:482
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 117:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:490
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 118:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:498
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 119:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:506
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 120:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:514
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 121:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:522
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 122:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:530
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 123:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:538
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 124:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:546
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 125:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:554
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 126:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:562
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 127:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:570
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 128:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:579
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 129:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:592
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 130:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:600
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[3].aexpr,
				Op:    yyDollar[2].str,
			}
		}
	case 131:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:608
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 132:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:718
		{
			yyVAL.aexpr = 1
		}
	case 133:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:720
		{
			yyVAL.aexpr = 1
		}
	case 134:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:722
		{
			yyVAL.aexpr = 1
		}
	case 135:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:724
		{
			yyVAL.aexpr = 1
		}
	case 136:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:743
		{
			yyVAL.aexpr = 1
		}
	case 137:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:745
		{
			yyVAL.aexpr = 1
		}
	case 138:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:747
		{
			yyVAL.aexpr = 1
		}
	case 139:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:749
		{
			yyVAL.aexpr = 1
		}
	case 140:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:769
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[5].aexpr,
				Op:    yyDollar[3].str,
			}
		}
	case 141:
		yyDollar = yyS[yypt-6 : yypt+1]
//line lyx/gram.y:777
		{
			yyVAL.aexpr = &AExprOp{
				Left:  yyDollar[1].aexpr,
				Right: yyDollar[6].aexpr,
				Op:    yyDollar[3].str,
			}
		}
	case 142:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:896
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 143:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:898
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 144:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:900
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 145:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:904
		{
			yyVAL.aexpr = yyDollar[1].aexpr
		}
	case 146:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:914
		{
			/*
			 * The SQL spec only allows DEFAULT in "contextually typed
			 * expressions", but for us, it's easier to allow it in
			 * any a_expr and then throw error during parse analysis
			 * if it's in an inappropriate context.  This way also
			 * lets us say something smarter than "syntax error".
			 */

		}
	case 147:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:928
		{
			yyVAL.colref = ColumnRef{
				ColName:    yyDollar[3].str,
				TableAlias: yyDollar[1].str,
			}
		}
	case 148:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:936
		{
			yyVAL.colref = ColumnRef{
				ColName: yyDollar[1].str,
			}
		}
	case 149:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:940
		{
			yyVAL.colref = yyDollar[1].colref
		}
	case 150:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:948
		{ /* result not matter */
		}
	case 151:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:950
		{ /* result not matter */
		}
	case 152:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:952
		{ /* result not matter */
		}
	case 153:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:954
		{ /* result not matter */
		}
	case 154:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:956
		{ /* result not matter */
		}
	case 155:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:958
		{ /* result not matter */
		}
	case 156:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:960
		{ /* result not matter */
		}
	case 157:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:962
		{ /* result not matter */
		}
	case 158:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:964
		{ /* result not matter */
		}
	case 159:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:966
		{ /* result not matter */
		}
	case 160:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:968
		{ /* result not matter */
		}
	case 161:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:970
		{ /* result not matter */
		}
	case 162:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:972
		{ /* result not matter */
		}
	case 163:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:974
		{ /* result not matter */
		}
	case 164:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:975
		{ /* result not matter */
		}
	case 165:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:980
		{
			yyVAL.aexpr = &AExprEmpty{}
		}
	case 166:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:984
		{
			yyVAL.aexpr = yyDollar[2].aexpr
		}
	case 167:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:989
		{
		}
	case 168:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:990
		{
		}
	case 169:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:994
		{
		}
	case 170:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:995
		{
		}
	case 171:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:999
		{

		}
	case 172:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1003
		{

		}
	case 173:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1007
		{

		}
	case 174:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1011
		{

		}
	case 175:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1018
		{
			yyVAL.statement = &VarSet{
				Name:  yyDollar[2].str,
				Value: yyDollar[4].str,
			}
		}
	case 176:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1024
		{
			yyVAL.statement = &VarSet{
				IsLocal: true,
				Name:    yyDollar[3].str,
				Value:   yyDollar[5].str,
			}
		}
	case 177:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1031
		{
		}
	case 178:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1032
		{
		}
	case 179:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1037
		{
			yyVAL.statement = &Begin{}
		}
	case 180:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1046
		{
			yyVAL.statement = &Commit{}
		}
	case 181:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1055
		{
			yyVAL.statement = &Rollback{}
		}
	case 182:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1063
		{
			yyVAL.statement = &Execute{
				Id: yyDollar[2].str,
			}
		}
	case 183:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1071
		{
			yyVAL.statement = &Execute{
				Id: yyDollar[2].str,
			}
		}
	case 184:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1078
		{
			yyVAL.statement = yyDollar[1].selectStmt
		}
	case 185:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1080
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 186:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1082
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 187:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1084
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 188:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1086
		{
			yyVAL.statement = yyDollar[1].statement
		}
	case 189:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1088
		{
			yyVAL.statement = &Explain{
				Stmt: yyDollar[2].statement,
			}
		}
	case 190:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1095
		{
		}
	case 191:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1096
		{
		}
	case 192:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1099
		{
		}
	case 193:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1100
		{
		}
	case 194:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1103
		{
			yyVAL.tableelt = []TableElt{{
				ColName: yyDollar[1].str,
				ColType: yyDollar[2].str,
			},
			}
		}
	case 195:
		yyDollar = yyS[yypt-6 : yypt+1]
//line lyx/gram.y:1110
		{
			yyVAL.tableelt = nil
		}
	case 196:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1113
		{
			yyVAL.tableelt = append(yyDollar[1].tableelt, yyDollar[3].tableelt...)
		}
	case 197:
		yyDollar = yyS[yypt-7 : yypt+1]
//line lyx/gram.y:1118
		{
			yyVAL.statement = &CreateTable{
				TableName: yyDollar[3].str,
				TableElts: yyDollar[5].tableelt,
			}
		}
	case 198:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1123
		{
			yyVAL.statement = &Index{}
		}
	case 199:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1127
		{
			yyVAL.statement = &CreateRole{}
		}
	case 200:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1131
		{
			yyVAL.statement = &CreateDatabase{}
		}
	case 201:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1138
		{
			yyVAL.statement = &Alter{}
		}
	case 202:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1145
		{
			yyVAL.statement = &Vacuum{}
		}
	case 203:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1152
		{
			yyVAL.statement = &Cluster{}
		}
	case 204:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1160
		{
			yyVAL.statement = &Analyze{}
		}
	case 205:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1167
		{
			yyVAL.statement = &Drop{}
		}
	case 206:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1175
		{
			yyVAL.statement = &Truncate{}
		}
	case 207:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1182
		{
		}
	case 208:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1182
		{
		}
	case 209:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1183
		{
		}
	case 210:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1183
		{
		}
	case 211:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1184
		{
		}
	case 212:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1184
		{
		}
	case 213:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1185
		{
		}
	case 214:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1185
		{
		}
	case 215:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1186
		{
		}
	case 216:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1186
		{
		}
	case 217:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1187
		{
		}
	case 218:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1187
		{
		}
	case 219:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1188
		{
		}
	case 220:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1188
		{
		}
	case 221:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1194
		{
			yyVAL.from_list = yyDollar[2].from_list
		}
	case 222:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1195
		{
		}
	case 223:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1199
		{
			yyVAL.from_list = []FromClauseNode{yyDollar[1].from}
		}
	case 224:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1200
		{
			yyVAL.from_list = append(yyDollar[1].from_list, yyDollar[3].from)
		}
	case 225:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1204
		{
			yyVAL.tableref = &RangeVar{
				SchemaName:   "",
				RelationName: yyDollar[1].str,
				Alias:        "",
			}
		}
	case 226:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1211
		{
			yyVAL.tableref = &RangeVar{
				SchemaName:   yyDollar[1].str,
				RelationName: yyDollar[3].str,
				Alias:        "",
			}
		}
	case 227:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1221
		{
			yyVAL.str = yyDollar[2].str
		}
	case 228:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1225
		{
			yyVAL.str = yyDollar[1].str
		}
	case 229:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1231
		{
			yyVAL.str = ""
		}
	case 231:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1239
		{
			yyDollar[1].tableref.SetAlias(yyDollar[2].str)
			yyVAL.from = yyDollar[1].tableref
		}
	case 232:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1244
		{
			yyVAL.from = yyDollar[1].tableref
		}
	case 233:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1248
		{
			yyDollar[2].tableref.SetAlias(yyDollar[4].str)
			yyVAL.from = yyDollar[2].tableref
		}
	case 234:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1256
		{
		}
	case 235:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1257
		{
		}
	case 236:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1261
		{
		}
	case 237:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1262
		{
		}
	case 238:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1263
		{
		}
	case 239:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1264
		{
		}
	case 240:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1275
		{

		}
	case 241:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1283
		{
			yyVAL.tableref = yyDollar[2].tableref
		}
	case 242:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1287
		{
			/* CROSS JOIN is same as unqualified inner join */
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[4].from,
			}
		}
	case 243:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1295
		{
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[4].from,
			}
		}
	case 244:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1302
		{
			/* letting join_type reduce to empty doesn't work */
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[3].from,
			}
		}
	case 245:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1310
		{
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[5].from,
			}
		}
	case 246:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lyx/gram.y:1317
		{
			/* letting join_type reduce to empty doesn't work */
			yyVAL.tableref = &JoinExpr{
				Larg: yyDollar[1].from,
				Rarg: yyDollar[4].from,
			}
		}
	case 247:
		yyDollar = yyS[yypt-11 : yypt+1]
//line lyx/gram.y:1332
		{
			yyVAL.selectStmt = &Select{
				FromClause: yyDollar[3].from_list,
				Where:      yyDollar[4].aexpr,
			}
		}
	case 248:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1337
		{
			yyVAL.selectStmt = &Select{}
		}
	case 249:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1344
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 250:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1345
		{
			yyVAL.strlist = append(yyDollar[3].strlist, yyDollar[1].str)
		}
	case 251:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1350
		{
		}
	case 252:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1350
		{
		}
	case 253:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1353
		{
			yyVAL.strlist = yyDollar[2].strlist
		}
	case 254:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1359
		{
		}
	case 255:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1360
		{
		}
	case 256:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1365
		{
			yyVAL.aexprList = []AExpr{yyDollar[1].aexpr}
		}
	case 257:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1367
		{
			yyVAL.aexprList = append(yyDollar[3].aexprList, yyDollar[1].aexpr)
		}
	case 258:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1372
		{
			yyVAL.aexprList = yyDollar[2].aexprList
		}
	case 259:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1378
		{
		}
	case 260:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1379
		{
		}
	case 261:
		yyDollar = yyS[yypt-7 : yypt+1]
//line lyx/gram.y:1385
		{
			yyVAL.statement = &Insert{
				TableRef: yyDollar[3].tableref,
				Columns:  yyDollar[4].strlist,
				Values:   yyDollar[6].aexprList,
			}
		}
	case 262:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lyx/gram.y:1391
		{
			yyVAL.statement = &Insert{
				TableRef:  yyDollar[3].tableref,
				SubSelect: yyDollar[5].selectStmt,
			}
		}
	case 263:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1399
		{
		}
	case 264:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1400
		{
		}
	case 265:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1403
		{
		}
	case 266:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1404
		{
		}
	case 267:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1410
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 268:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1411
		{
			yyVAL.strlist = append(yyDollar[1].strlist, yyDollar[3].str)
		}
	case 269:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1416
		{
			yyVAL.str = yyDollar[1].str
		}
	case 270:
		yyDollar = yyS[yypt-8 : yypt+1]
//line lyx/gram.y:1426
		{
			yyVAL.statement = &Update{
				TableRef: yyDollar[3].tableref,
				Where:    yyDollar[7].aexpr,
			}
		}
	case 271:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lyx/gram.y:1437
		{
			yyVAL.strlist = []string{yyDollar[1].str}
		}
	case 272:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lyx/gram.y:1438
		{
			yyVAL.strlist = append(yyDollar[3].strlist, yyDollar[1].str)
		}
	case 273:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lyx/gram.y:1443
		{
		}
	case 274:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lyx/gram.y:1444
		{
		}
	case 275:
		yyDollar = yyS[yypt-7 : yypt+1]
//line lyx/gram.y:1448
		{
			yyVAL.statement = &Delete{
				TableRef: yyDollar[4].tableref,
				Where:    yyDollar[6].aexpr,
			}
		}
	case 276:
		yyDollar = yyS[yypt-6 : yypt+1]
//line lyx/gram.y:1457
		{
			yyVAL.statement = &Copy{
				TableRef: yyDollar[2].tableref,
				Where:    yyDollar[6].aexpr,
				IsFrom:   false,
			}
		}
	}
	goto yystack /* stack new state and value */
}
